use crate::typeck::term::TypeTerm;

pub(crate) fn infer_methods_package_call_term(
    callee: &str,
    _arg_terms: &[TypeTerm],
) -> Option<TypeTerm> {
    match callee {
        "methods::isClass"
        | "methods::isGeneric"
        | "methods::hasMethod"
        | "methods::existsMethod"
        | "methods::existsFunction"
        | "methods::hasLoadAction"
        | "methods::hasArg"
        | "methods::hasMethods"
        | "methods::isGroup"
        | "methods::isGrammarSymbol"
        | "methods::isRematched"
        | "methods::isXS3Class"
        | "methods::is"
        | "methods::validObject"
        | "methods::isVirtualClass"
        | "methods::isClassUnion"
        | "methods::isSealedClass"
        | "methods::isSealedMethod"
        | "methods::isClassDef"
        | "methods::testVirtual"
        | "methods::canCoerce" => Some(TypeTerm::Logical),
        "methods::slotNames"
        | "methods::getClasses"
        | "methods::getSlots"
        | "methods::getGroupMembers"
        | "methods::formalArgs"
        | "methods::getAllSuperClasses" => Some(TypeTerm::Vector(Box::new(TypeTerm::Char))),
        "methods::getPackageName" => Some(TypeTerm::Char),
        "methods::getClass"
        | "methods::getClassDef"
        | "methods::findMethods"
        | "methods::findClass"
        | "methods::findUnique" => Some(TypeTerm::List(Box::new(TypeTerm::Any))),
        "methods::classesToAM" => Some(TypeTerm::Matrix(Box::new(TypeTerm::Double))),
        "methods::findMethodSignatures" => Some(TypeTerm::Matrix(Box::new(TypeTerm::Char))),
        "methods::cacheMetaData" => Some(TypeTerm::Null),
        "methods::getLoadActions" => Some(TypeTerm::List(Box::new(TypeTerm::Any))),
        "methods::extends" => Some(TypeTerm::Vector(Box::new(TypeTerm::Char))),
        "methods::getGenerics" | "methods::getGroup" => {
            Some(TypeTerm::List(Box::new(TypeTerm::Any)))
        }
        "methods::findMethod" | "methods::getMethodsForDispatch" => {
            Some(TypeTerm::List(Box::new(TypeTerm::Any)))
        }
        "methods::setGeneric" | "methods::setMethod" => Some(TypeTerm::Char),
        "methods::showExtends"
        | "methods::addNextMethod"
        | "methods::makeExtends"
        | "methods::setAs"
        | "methods::resetClass"
        | "methods::assignMethodsMetaData"
        | "methods::signature"
        | "methods::setReplaceMethod"
        | "methods::removeClass"
        | "methods::implicitGeneric"
        | "methods::el"
        | "methods::callGeneric"
        | "methods::showClass"
        | "methods::Complex"
        | "methods::evalSource"
        | "methods::coerce<-"
        | "methods::kronecker"
        | "methods::resetGeneric"
        | "methods::matrixOps"
        | "methods::possibleExtends"
        | "methods::missingArg"
        | "methods::Quote"
        | "methods::registerImplicitGenerics"
        | "methods::initRefFields"
        | "methods::insertMethod"
        | "methods::externalRefMethod"
        | "methods::fixPre1.8"
        | "methods::checkAtAssignment"
        | "methods::finalDefaultMethod"
        | "methods::completeClassDefinition"
        | "methods::callNextMethod"
        | "methods::selectSuperClasses"
        | "methods::removeMethods"
        | "methods::evalOnLoad"
        | "methods::cbind2"
        | "methods::setClassUnion"
        | "methods::initialize"
        | "methods::Summary"
        | "methods::representation"
        | "methods::method.skeleton"
        | "methods::setRefClass"
        | "methods::Math2"
        | "methods::getMethods"
        | "methods::S3Part<-"
        | "methods::Logic"
        | "methods::matchSignature"
        | "methods::methodsPackageMetaName"
        | "methods::defaultDumpName"
        | "methods::substituteDirect"
        | "methods::packageSlot"
        | "methods::as<-"
        | "methods::removeMethod"
        | "methods::MethodsListSelect"
        | "methods::S3Part"
        | "methods::checkSlotAssignment"
        | "methods::classMetaName"
        | "methods::slotsFromS3"
        | "methods::promptMethods"
        | "methods::insertClassMethods"
        | "methods::packageSlot<-"
        | "methods::languageEl<-" => Some(TypeTerm::Any),
        "methods::.slotNames" => Some(TypeTerm::Vector(Box::new(TypeTerm::Char))),
        "methods::.hasSlot" => Some(TypeTerm::Logical),
        "methods::validSlotNames" | "methods::inheritedSlotNames" | "methods::allNames" => {
            Some(TypeTerm::Vector(Box::new(TypeTerm::Char)))
        }
        "methods::classLabel" | "methods::className" | "methods::setPackageName" => {
            Some(TypeTerm::Char)
        }
        "methods::.__C__signature"
        | "methods::.__C__packageInfo"
        | "methods::.__C__MethodSelectionReport"
        | "methods::.__C__uninitializedField"
        | "methods::.__C__ordered"
        | "methods::.__C__oldClass"
        | "methods::.__C__groupGenericFunction"
        | "methods::.__C__standardGeneric"
        | "methods::.__C__nonstandardGroupGenericFunction"
        | "methods::.__C__S3"
        | "methods::.__C__array"
        | "methods::.__C__S4"
        | "methods::.__C__SuperClassMethod"
        | "methods::.__C__aov"
        | "methods::.__C__integrate"
        | "methods::.__C__listOfMethods"
        | "methods::.__C__ClassUnionRepresentation"
        | "methods::.__C__refObject"
        | "methods::.__C__.Other"
        | "methods::.__C__classPrototypeDef"
        | "methods::.__C__ts"
        | "methods::.__C__table"
        | "methods::.__C__double"
        | "methods::.__C__environment"
        | "methods::.__C__Date"
        | "methods::.__C__character"
        | "methods::.__C__LinearMethodsList"
        | "methods::.__C__structure"
        | "methods::.__C__lm"
        | "methods::.__C__dump.frames"
        | "methods::.__C__density"
        | "methods::.__C__vector"
        | "methods::.__C__repeat"
        | "methods::.__C__className"
        | "methods::.__C__name"
        | "methods::.__C__ObjectsWithPackage"
        | "methods::.__C__glm.null"
        | "methods::.__C__defaultBindingFunction"
        | "methods::.__C__("
        | "methods::.__C__special"
        | "methods::.__C__SealedMethodDefinition"
        | "methods::.__C__list"
        | "methods::.__C__NULL"
        | "methods::.__C__.environment"
        | "methods::.__C__genericFunctionWithTrace"
        | "methods::.__C__anova"
        | "methods::.__C__socket"
        | "methods::.__C__refGeneratorSlot"
        | "methods::.__C__integer"
        | "methods::.__C__packageIQR"
        | "methods::.__C__envRefClass"
        | "methods::.__C__complex"
        | "methods::.__C__classRepresentation"
        | "methods::.__C__libraryIQR"
        | "methods::.__C__OptionalFunction"
        | "methods::.__C__missing"
        | "methods::.__C__refMethodDef"
        | "methods::.__C__genericFunction"
        | "methods::.__C__classGeneratorFunction"
        | "methods::.__C__raw"
        | "methods::.__C__mlm"
        | "methods::.__C__POSIXct"
        | "methods::.__C__{"
        | "methods::.__C__groupGenericFunctionWithTrace"
        | "methods::.__C__data.frameRowLabels"
        | "methods::.__C__activeBindingFunction"
        | "methods::.__C__externalptr"
        | "methods::.__C__.name"
        | "methods::.__C__recordedplot"
        | "methods::.__C__localRefClass"
        | "methods::.__C__POSIXt"
        | "methods::.__C__summary.table"
        | "methods::.__C__language"
        | "methods::.__C__refClass"
        | "methods::.__C__numeric"
        | "methods::.__C__derivedDefaultMethodWithTrace"
        | "methods::.__C__externalRefMethod"
        | "methods::.__C__MethodDefinitionWithTrace"
        | "methods::.__C__maov"
        | "methods::.__C__standardGenericWithTrace"
        | "methods::.__C__.NULL"
        | "methods::.__C__PossibleMethod"
        | "methods::.__C__functionWithTrace"
        | "methods::.__C__factor"
        | "methods::.__C__sourceEnvironment"
        | "methods::.__C__MethodDefinition"
        | "methods::.__C__mts"
        | "methods::.__C__mtable"
        | "methods::.__C__data.frame"
        | "methods::.__C__if"
        | "methods::.__C__optionalMethod"
        | "methods::.__C__ANY"
        | "methods::.__C__refClassRepresentation"
        | "methods::.__C__conditionalExtension"
        | "methods::.__C__traceable"
        | "methods::.__C__MethodWithNextWithTrace"
        | "methods::.__C__anova.glm.null"
        | "methods::.__C__.externalptr"
        | "methods::.__C__matrix"
        | "methods::.__C__hsearch"
        | "methods::.__C__function"
        | "methods::.__C__POSIXlt"
        | "methods::.__C__logical"
        | "methods::.__C__nonstandardGenericWithTrace"
        | "methods::.__C__summaryDefault"
        | "methods::.__C__derivedDefaultMethod"
        | "methods::.__C__nonstandardGeneric"
        | "methods::.__C__glm"
        | "methods::.__C__nonstandardGenericFunction"
        | "methods::.__C__refObjectGenerator"
        | "methods::.__C__builtin"
        | "methods::.__C__for"
        | "methods::.__C__internalDispatchMethod"
        | "methods::.__C__anova.glm"
        | "methods::.__C__<-"
        | "methods::.__C__nonStructure"
        | "methods::.__C__call"
        | "methods::.__C__MethodWithNext"
        | "methods::.__C__rle"
        | "methods::.__C__logLik"
        | "methods::.__C__namedList"
        | "methods::.__C__formula"
        | "methods::.__C__while"
        | "methods::.__C__expression"
        | "methods::.__C__refMethodDefWithTrace"
        | "methods::.__C__VIRTUAL"
        | "methods::.__C__SClassExtension" => Some(TypeTerm::Any),
        "methods::.EmptyPrimitiveSkeletons"
        | "methods::.OldClassesList"
        | "methods::.S4methods"
        | "methods::.ShortPrimitiveSkeletons"
        | "methods::.classEnv"
        | "methods::.doTracePrint"
        | "methods::.selectSuperClasses"
        | "methods::.untracedFunction"
        | "methods::.valueClassTest"
        | "methods::.__T__Logic:base"
        | "methods::.__T__loadMethod:methods"
        | "methods::.__T__[<-:base"
        | "methods::.__T__coerce:methods"
        | "methods::.__T__matrixOps:base"
        | "methods::.__T__show:methods"
        | "methods::.__T__body<-:base"
        | "methods::.__T__cbind2:methods"
        | "methods::.__T__Arith:base"
        | "methods::.__T__[[<-:base"
        | "methods::.__T__$:base"
        | "methods::.__T__Compare:methods"
        | "methods::.__T__Math2:methods"
        | "methods::.__T__slotsFromS3:methods"
        | "methods::.__T__Complex:base"
        | "methods::.__T__coerce<-:methods"
        | "methods::.__T__kronecker:base"
        | "methods::.__T__rbind2:methods"
        | "methods::.__T__initialize:methods"
        | "methods::.__T__$<-:base"
        | "methods::.__T__addNextMethod:methods"
        | "methods::.__T__Ops:base"
        | "methods::.__T__Math:base"
        | "methods::.__T__Summary:base"
        | "methods::.__T__[:base"
        | "methods::emptyMethodsList"
        | "methods::listFromMethods"
        | "methods::metaNameUndo"
        | "methods::Math"
        | "methods::makePrototypeFromClassDef"
        | "methods::reconcilePropertiesAndPrototype"
        | "methods::doPrimitiveMethod"
        | "methods::SignatureMethod"
        | "methods::setIs"
        | "methods::balanceMethodsList"
        | "methods::setLoadActions"
        | "methods::setDataPart"
        | "methods::setGroupGeneric"
        | "methods::S3Class"
        | "methods::dumpMethods"
        | "methods::sigToEnv"
        | "methods::setGenericImplicit"
        | "methods::sealClass"
        | "methods::makeStandardGeneric"
        | "methods::loadMethod"
        | "methods::prohibitGeneric"
        | "methods::substituteFunctionArgs"
        | "methods::completeExtends"
        | "methods::assignClassDef"
        | "methods::methodSignatureMatrix"
        | "methods::body<-"
        | "methods::prototype"
        | "methods::requireMethods"
        | "methods::slot<-"
        | "methods::setOldClass"
        | "methods::setPrimitiveMethods"
        | "methods::rematchDefinition"
        | "methods::MethodAddCoerce"
        | "methods::evalqOnLoad"
        | "methods::insertSource"
        | "methods::multipleClasses"
        | "methods::empty.dump"
        | "methods::el<-"
        | "methods::elNamed<-"
        | "methods::newEmptyObject"
        | "methods::Arith"
        | "methods::mergeMethods"
        | "methods::MethodsList"
        | "methods::asMethodDefinition"
        | "methods::languageEl"
        | "methods::Ops"
        | "methods::completeSubclasses"
        | "methods::cacheGenericsMetaData"
        | "methods::tryNew"
        | "methods::showDefault"
        | "methods::Compare"
        | "methods::makeClassRepresentation"
        | "methods::promptClass"
        | "methods::newClassRepresentation"
        | "methods::removeGeneric"
        | "methods::S3Class<-"
        | "methods::rbind2"
        | "methods::setValidity"
        | "methods::functionBody"
        | "methods::dumpMethod"
        | "methods::elNamed"
        | "methods::generic.skeleton"
        | "methods::makeGeneric"
        | "methods::coerce"
        | "methods::initFieldArgs"
        | "methods::unRematchDefinition"
        | "methods::defaultPrototype"
        | "methods::showMethods"
        | "methods::as"
        | "methods::conformMethod"
        | "methods::makeMethodsList"
        | "methods::newBasic"
        | "methods::functionBody<-"
        | "methods::setLoadAction"
        | "methods::superClassDepth"
        | "methods::getMethodsMetaData" => Some(TypeTerm::Any),
        "methods::getGeneric"
        | "methods::cacheMethod"
        | "methods::getFunction"
        | "methods::getRefClass"
        | "methods::findFunction"
        | "methods::getDataPart"
        | "methods::selectMethod"
        | "methods::new"
        | "methods::slot"
        | "methods::getMethod"
        | "methods::getValidity"
        | "methods::testInheritedMethods"
        | "methods::standardGeneric"
        | "methods::setClass" => Some(TypeTerm::Any),
        "methods::show" => Some(TypeTerm::Null),
        _ => None,
    }
}
