#[path = "tests/assign_callmap.rs"]
pub(crate) mod assign_callmap;
#[path = "tests/binding_branches.rs"]
pub(crate) mod binding_branches;
#[path = "tests/binding_origins.rs"]
pub(crate) mod binding_origins;
#[path = "tests/common.rs"]
pub(crate) mod common;
pub(crate) use self::common::*;
#[path = "tests/cse.rs"]
pub(crate) mod cse;
#[path = "tests/freshness.rs"]
pub(crate) mod freshness;
#[path = "tests/full_range.rs"]
pub(crate) mod full_range;
#[path = "tests/index_reads.rs"]
pub(crate) mod index_reads;
#[path = "tests/structured_render.rs"]
pub(crate) mod structured_render;
