pub(crate) fn contains(name: &str) -> bool {
    matches!(
        name,
        "parallel::detectCores"
            | "parallel::makeCluster"
            | "parallel::makeForkCluster"
            | "parallel::makePSOCKcluster"
            | "parallel::stopCluster"
            | "parallel::parLapply"
            | "parallel::parLapplyLB"
            | "parallel::parCapply"
            | "parallel::parRapply"
            | "parallel::pvec"
            | "parallel::clusterExport"
            | "parallel::clusterEvalQ"
            | "parallel::clusterSetRNGStream"
            | "parallel::clusterMap"
            | "parallel::clusterApply"
            | "parallel::clusterCall"
            | "parallel::mclapply"
            | "parallel::mcMap"
            | "parallel::mcmapply"
            | "parallel::mc.reset.stream"
            | "parallel::mcaffinity"
            | "parallel::clusterSplit"
            | "parallel::splitIndices"
            | "parallel::clusterApplyLB"
            | "parallel::parSapply"
            | "parallel::parSapplyLB"
            | "parallel::parApply"
            | "parallel::mcparallel"
            | "parallel::mccollect"
            | "parallel::closeNode"
            | "parallel::recvData"
            | "parallel::recvOneData"
            | "parallel::sendData"
            | "parallel::getDefaultCluster"
            | "parallel::setDefaultCluster"
            | "parallel::registerClusterType"
            | "parallel::nextRNGStream"
            | "parallel::nextRNGSubStream"
    )
}
