pub(crate) fn contains(name: &str) -> bool {
    matches!(
        name,
        "stats4::mle"
            | "stats4::coef"
            | "stats4::vcov"
            | "stats4::confint"
            | "stats4::logLik"
            | "stats4::AIC"
            | "stats4::BIC"
            | "stats4::nobs"
            | "stats4::update"
            | "stats4::summary"
            | "stats4::profile"
            | "stats4::plot"
            | "stats4::show"
            | "stats4::.__C__mle"
            | "stats4::.__C__profile.mle"
            | "stats4::.__C__summary.mle"
            | "stats4::.__T__AIC:stats"
            | "stats4::.__T__BIC:stats"
            | "stats4::.__T__coef:stats"
            | "stats4::.__T__confint:stats"
            | "stats4::.__T__logLik:stats"
            | "stats4::.__T__nobs:stats"
            | "stats4::.__T__plot:base"
            | "stats4::.__T__profile:stats"
            | "stats4::.__T__show:methods"
            | "stats4::.__T__summary:base"
            | "stats4::.__T__update:stats"
            | "stats4::.__T__vcov:stats"
    )
}
