use crate::typeck::builtin_sigs::{
    first_arg_type_state, infer_builtin, preserved_first_arg_type_without_len,
};
use crate::typeck::lattice::{PrimTy, TypeState};

pub(crate) fn infer_base_package_call(callee: &str, arg_tys: &[TypeState]) -> Option<TypeState> {
    match callee {
        "base::length" => infer_builtin("length", arg_tys),
        "base::seq_len" => Some(TypeState::vector(PrimTy::Int, true)),
        "base::seq_along" => infer_builtin("seq_along", arg_tys),
        "base::c" => infer_builtin("c", arg_tys),
        "base::list" => infer_builtin("list", arg_tys),
        "base::sum" => infer_builtin("sum", arg_tys),
        "base::mean" => infer_builtin("mean", arg_tys),
        "base::abs" => infer_builtin("abs", arg_tys),
        "base::seq" => infer_builtin("seq", arg_tys),
        "base::ifelse" => infer_builtin("ifelse", arg_tys),
        "base::min" => infer_builtin("min", arg_tys),
        "base::max" => infer_builtin("max", arg_tys),
        "base::pmax" => infer_builtin("pmax", arg_tys),
        "base::pmin" => infer_builtin("pmin", arg_tys),
        "base::sqrt" => infer_builtin("sqrt", arg_tys),
        "base::log" => infer_builtin("log", arg_tys),
        "base::log10" => infer_builtin("log10", arg_tys),
        "base::log2" => infer_builtin("log2", arg_tys),
        "base::exp" => infer_builtin("exp", arg_tys),
        "base::atan2" => infer_builtin("atan2", arg_tys),
        "base::sin" => infer_builtin("sin", arg_tys),
        "base::cos" => infer_builtin("cos", arg_tys),
        "base::tan" => infer_builtin("tan", arg_tys),
        "base::asin" => infer_builtin("asin", arg_tys),
        "base::acos" => infer_builtin("acos", arg_tys),
        "base::atan" => infer_builtin("atan", arg_tys),
        "base::sinh" => infer_builtin("sinh", arg_tys),
        "base::cosh" => infer_builtin("cosh", arg_tys),
        "base::tanh" => infer_builtin("tanh", arg_tys),
        "base::sign" => infer_builtin("sign", arg_tys),
        "base::gamma" => infer_builtin("gamma", arg_tys),
        "base::lgamma" => infer_builtin("lgamma", arg_tys),
        "base::floor" => infer_builtin("floor", arg_tys),
        "base::ceiling" => infer_builtin("ceiling", arg_tys),
        "base::trunc" => infer_builtin("trunc", arg_tys),
        "base::round" => infer_builtin("round", arg_tys),
        "base::is.na" => infer_builtin("is.na", arg_tys),
        "base::is.finite" => infer_builtin("is.finite", arg_tys),
        "base::print" => Some(preserved_first_arg_type_without_len(first_arg_type_state(
            arg_tys,
        ))),
        callee if callee.starts_with("base::print.") => Some(preserved_first_arg_type_without_len(
            first_arg_type_state(arg_tys),
        )),
        "base::numeric" => infer_builtin("numeric", arg_tys),
        "base::matrix" => infer_builtin("matrix", arg_tys),
        "base::diag" => infer_builtin("diag", arg_tys),
        "base::t" => infer_builtin("t", arg_tys),
        "base::rbind" => infer_builtin("rbind", arg_tys),
        "base::cbind" => infer_builtin("cbind", arg_tys),
        "base::rowSums" => infer_builtin("rowSums", arg_tys),
        "base::colSums" => infer_builtin("colSums", arg_tys),
        "base::crossprod" => infer_builtin("crossprod", arg_tys),
        "base::tcrossprod" => infer_builtin("tcrossprod", arg_tys),
        "base::dim" => infer_builtin("dim", arg_tys),
        "base::dimnames" => infer_builtin("dimnames", arg_tys),
        "base::nrow" => infer_builtin("nrow", arg_tys),
        "base::ncol" => infer_builtin("ncol", arg_tys),
        "base::character" => infer_builtin("character", arg_tys),
        "base::logical" => infer_builtin("logical", arg_tys),
        "base::integer" => infer_builtin("integer", arg_tys),
        "base::double" => infer_builtin("double", arg_tys),
        "base::rep" => infer_builtin("rep", arg_tys),
        "base::rep.int" => infer_builtin("rep.int", arg_tys),
        "base::any" => infer_builtin("any", arg_tys),
        "base::all" => infer_builtin("all", arg_tys),
        "base::which" => infer_builtin("which", arg_tys),
        "base::prod" => infer_builtin("prod", arg_tys),
        "base::paste" => infer_builtin("paste", arg_tys),
        "base::paste0" => infer_builtin("paste0", arg_tys),
        "base::sprintf" => infer_builtin("sprintf", arg_tys),
        "base::cat" => infer_builtin("cat", arg_tys),
        "base::tolower" => infer_builtin("tolower", arg_tys),
        "base::toupper" => infer_builtin("toupper", arg_tys),
        "base::substr" => infer_builtin("substr", arg_tys),
        "base::sub" => infer_builtin("sub", arg_tys),
        "base::gsub" => infer_builtin("gsub", arg_tys),
        "base::nchar" => infer_builtin("nchar", arg_tys),
        "base::nzchar" => infer_builtin("nzchar", arg_tys),
        "base::grepl" => infer_builtin("grepl", arg_tys),
        "base::grep" => infer_builtin("grep", arg_tys),
        "base::startsWith" => infer_builtin("startsWith", arg_tys),
        "base::endsWith" => infer_builtin("endsWith", arg_tys),
        "base::which.min" => infer_builtin("which.min", arg_tys),
        "base::which.max" => infer_builtin("which.max", arg_tys),
        "base::isTRUE" => infer_builtin("isTRUE", arg_tys),
        "base::isFALSE" => infer_builtin("isFALSE", arg_tys),
        "base::lengths" => infer_builtin("lengths", arg_tys),
        "base::union" => infer_builtin("union", arg_tys),
        "base::intersect" => infer_builtin("intersect", arg_tys),
        "base::setdiff" => infer_builtin("setdiff", arg_tys),
        "base::sample" => infer_builtin("sample", arg_tys),
        "base::sample.int" => infer_builtin("sample.int", arg_tys),
        "base::rank" => infer_builtin("rank", arg_tys),
        "base::factor" => infer_builtin("factor", arg_tys),
        "base::cut" => infer_builtin("cut", arg_tys),
        "base::table" => infer_builtin("table", arg_tys),
        "base::trimws" => infer_builtin("trimws", arg_tys),
        "base::chartr" => infer_builtin("chartr", arg_tys),
        "base::strsplit" => infer_builtin("strsplit", arg_tys),
        "base::regexpr" => infer_builtin("regexpr", arg_tys),
        "base::gregexpr" => infer_builtin("gregexpr", arg_tys),
        "base::regexec" => infer_builtin("regexec", arg_tys),
        "base::agrep" => infer_builtin("agrep", arg_tys),
        "base::agrepl" => infer_builtin("agrepl", arg_tys),
        "base::names" => infer_builtin("names", arg_tys),
        "base::rownames" => infer_builtin("rownames", arg_tys),
        "base::colnames" => infer_builtin("colnames", arg_tys),
        "base::sort" => infer_builtin("sort", arg_tys),
        "base::order" => infer_builtin("order", arg_tys),
        "base::match" => infer_builtin("match", arg_tys),
        "base::unique" => infer_builtin("unique", arg_tys),
        "base::duplicated" => infer_builtin("duplicated", arg_tys),
        "base::anyDuplicated" => infer_builtin("anyDuplicated", arg_tys),
        "base::summary" => Some(TypeState::vector(PrimTy::Any, false)),
        callee if callee.starts_with("base::summary.") => Some(TypeState::unknown()),
        _ => None,
    }
}
